=== neuharthr/mediasolv/lmm/JavaSource/swingbeanformbuilder/sbfb.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT allowed-value EMPTY>
<!ATTLIST allowed-value
	value CDATA #REQUIRED
	label CDATA #IMPLIED
>
<!--
Entity to begin a class definition. A class definition let you 
define how this class will be layed out by SBFB.

This tag also let you bind a custom component on a specific
class type (when nested in another class, eg: bind all java.util.Date
instances on a custom JDatePicker component).
-->
<!ELEMENT class (field*,group*,field*,group*)> 
<!ATTLIST class name CDATA #REQUIRED> 
<!ATTLIST class label CDATA #IMPLIED>
<!ATTLIST class icon CDATA #IMPLIED>
<!ATTLIST class custom-component CDATA #IMPLIED>

<!ELEMENT date-format EMPTY>
<!ATTLIST date-format
	value CDATA #REQUIRED
>
<!ELEMENT default-builder EMPTY>
<!ATTLIST default-builder
	class-name CDATA #REQUIRED
>
<!ELEMENT new-label EMPTY>
<!ATTLIST new-label
	value CDATA #REQUIRED
>
<!ELEMENT modify-label EMPTY>
<!ATTLIST modify-label
	value CDATA #REQUIRED
>

<!ELEMENT delete-label EMPTY>
<!ATTLIST delete-label
	value CDATA #REQUIRED
>
<!ELEMENT field (allowed-value*)>
<!ATTLIST field
	name CDATA #REQUIRED
	visible CDATA #IMPLIED
	bold-label CDATA #IMPLIED
	maxlength CDATA #IMPLIED
	fill CDATA #IMPLIED
	last-of-line CDATA #IMPLIED
	type CDATA #IMPLIED
	selection-mode CDATA #IMPLIED
	class-name CDATA #IMPLIED
	column-spanned CDATA #IMPLIED
	label CDATA #IMPLIED
	background-color CDATA #IMPLIED
	custom-component CDATA #IMPLIED
	last-of-line (true|false) "true"
	render CDATA #IMPLIED
	label-color CDATA #IMPLIED
	password CDATA #IMPLIED
	tool-tip CDATA #IMPLIED
>
<!ELEMENT group (field+)>
<!ATTLIST group
	name CDATA #IMPLIED
	label CDATA #IMPLIED
	show-banner CDATA #IMPLIED
	render CDATA #IMPLIED
	last-of-line CDATA #IMPLIED
	fill CDATA #IMPLIED
	border CDATA #IMPLIED 
>
<!ELEMENT root (default-builder*, date-format*, new-label*, modify-label*, delete-label*, class*)>

=== neuharthr/mediasolv/lmm/JavaSource/swingbeanformbuilder/demo/sbfb-demo-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "sbfb.dtd">
<root>
	<default-builder class-name="swingbeanformbuilder.core.services.impl.SwingSBFBFormBuilderImpl" />
    <date-format value="MM/dd/yyyy" />
    <new-label value="Add new" />
    <modify-label value="Modify" />    	
    <delete-label value="Remove" />
    <class name="swingbeanformbuilder.demo.DemoBean" label="Person informations" icon="resources/bart.gif">
        <field name="id" visible="false" />
        <field name="firstname" maxlength="20" fill="horizontal" last-of-line="false" />
        <field name="lastname" maxlength="20" fill="horizontal" bold-label="true" tool-tip="This is good!"/>
		<group render="innerPanel" show-banner="false" label="You can label inner groups">       
	        <field name="age" fill="none" maxlength="3" background-color="#DDFFDD" last-of-line="false" />
<!--        <field name="birthday" custom-component="swingbeanformbuilder.gui.swing.form.components.swingx.SBFBCustomDatePicker" fill="none" /> -->
	        <field name="sexe" fill="none" type="radio">
	            <allowed-value value="M" label="Male" />
	            <allowed-value value="F" label="Female" />
	        </field>	        	        
        </group>
    	<group render="innerPanel" show-banner="false" last-of-line="false" fill="none" border="none">
	    	<field name="client" last-of-line="false" fill="none" />
	    	<field name="prospect" fill="none" last-of-line="false" />
	        <field name="active" render="toggle" /> 	    	
		</group>    	
    	<field name="rate" fill="none" />            
    	<field name="dad" last-of-line="false" />                 
        <field name="contrat" label="Contract type">
            <allowed-value value="CDI" />
            <allowed-value value="CDD" />        
        </field>    	
        <field name="friends" fill="both" selection-mode="multiple" class-name="swingbeanformbuilder.demo.DemoBean" render="table" label-color="#0000FF" bold-label="true" /> 			
        <group name="image" label="Image example" show-banner="true">
	    	<field name="drink" type="image" label="Favourite Drink" />
	        <field name="comments" fill="both" />	    	
    	</group>
		<group name="attributs" label="Banking informations" show-banner="true">
	        <field name="iBAN" column-spanned="3" />
			<field name="bankingComments" fill="both" label="Comments" />	              	
        </group>
    </class> 
</root>
